name: Download Android apk
on:
  pull_request:
    types: [labeled]
jobs:
  if: contains(github.event.pull_request.labels.*.name, 'create-builds')
  download-apk:
    runs-on: ubuntu-latest
    steps:
      - name: download metmask apk from github
        run: |
          RELEASE_INFO=$(curl -s -H "Authorization: token $GITHUB_PERSONAL_ACCESS_TOKEN" \
          "https://api.github.com/repos/MetaMask/metamask-mobile/releases/latest")

          echo "$RELEASE_INFO"