name: Download Android apk
on:
  pull_request:
    types: [labeled]
jobs:
  download-apk:
    if: contains(github.event.pull_request.labels.*.name, 'create-builds')
    runs-on: ubuntu-latest
    steps:
      - name: download metmask apk from github
        run: |
          RELEASE_INFO=$(curl -s -H "Authorization: token ${{ secrets.MAESTRO_PAT_FOR_APK_DOWNLOAD }}" \
          "https://api.github.com/repos/MetaMask/metamask-mobile/releases/latest")

          echo "$RELEASE_INFO"