name: Setup Android Emulator
run-name: ${{ github.actor }} is testing setting up an emulator on GitHub Actions 🚀
on: 
  pull_request:
    types: [labeled]

jobs:
  create-emulator:
    if: contains(github.event.pull_request.labels.*.name, 'create-emulator')
    runs-on: macos-latest
    steps:
      - name: Install Brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install JDK
        run: |
          brew install openjdk@17
          echo 'export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"' >> /Users/runner/.bash_profile
      - name: Install SDK command line tools
        run: |
         mkdir -p ~/Android/sdk
         cd ~/Android/sdk
         wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
         unzip commandlinetools-linux-9477386_latest.zip
         mv cmdline-tools latest
         mkdir tools
         mv latest tools/cmdline-tools
         export ANDROID_HOME=$HOME/android-sdk
         export PATH=$ANDROID_HOME/tools/cmdline-tools/bin:$PATH
         export PATH=$ANDROID_HOME/platform-tools:$PATH
         echo $ANDROID_HOME